---

- name: Set common default variables
  ansible.builtin.import_role:
    name: common

- name: Create service directory
  ansible.builtin.file:
    state: directory
    path: /opt/mediastack/flaresolverr
    owner: root
    group: docker
    mode: "0755"

- name: Create service definition file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/mediastack/flaresolverr/docker-compose.yml
    owner: root
    group: docker
    mode: "0640"
  notify: stop flaresolverr

- name: Validate service definition file
  ansible.builtin.command:
    cmd: docker compose --file docker-compose.yml config --quiet
    chdir: /opt/mediastack/flaresolverr
  changed_when: false

- name: Flush handlers (to stop service as required)
  ansible.builtin.meta: flush_handlers

- name: Start service
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain --file docker-compose.yml up --detach
    chdir: /opt/mediastack/flaresolverr
  register: mediastack_temp_service_start
  changed_when: "'Started' in mediastack_temp_service_start.stdout"

- name: Wait for service to be accessible
  ansible.builtin.uri:
    url: "http://localhost:{{ mediastack_flaresolverr_host_port }}"
    status_code:
      - 200
      - 302
  register: mediastack_temp_service_test
  until: mediastack_temp_service_test is not failed
  retries: 300
  delay: 1
