---

- name: Set common default variables
  ansible.builtin.import_role:
    name: common

- name: Create service directory
  ansible.builtin.file:
    state: directory
    path: /opt/mediastack/prowlarr
    owner: root
    group: docker
    mode: "0755"

- name: Create configuration directory
  ansible.builtin.file:
    state: directory
    path: /opt/mediastack/prowlarr/config
    owner: mediastack
    group: mediastack
    mode: "0750"

- name: Create service definition file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/mediastack/prowlarr/docker-compose.yml
    owner: root
    group: docker
    mode: "0640"
  notify: stop prowlarr

- name: Validate service definition file
  ansible.builtin.command:
    cmd: docker compose --file docker-compose.yml config --quiet
    chdir: /opt/mediastack/prowlarr
  changed_when: false

- name: Flush handlers (to stop service as required)
  ansible.builtin.meta: flush_handlers

- name: Start service
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain --file docker-compose.yml up --detach
    chdir: /opt/mediastack/prowlarr
  register: mediastack_temp_service_start
  changed_when: "'Started' in mediastack_temp_service_start.stdout"

- name: Wait for service to be accessible
  ansible.builtin.uri:
    url: "http://localhost:{{ mediastack_prowlarr_host_port }}"
    status_code:
      - 200
      - 302
  register: mediastack_temp_service_test
  until: mediastack_temp_service_test is not failed
  retries: 300
  delay: 1
